name:                basic-authentication
version:             0.1.0.0
github:              "arkon92/basic-authentication"
author:              "arkon92"


description:         A basic authentication service

dependencies:
  - base >= 4.7 && < 5
  - happstack-server
  - base64-bytestring
  - bytestring
  - HUnit

library:
  source-dirs: src

executables:
  basic-authentication-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - basic-authentication

tests:
  basic-authentication-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - basic-authentication
